<a href="https://colab.research.google.com/github/bbash/ArewaDS-Deep-Learning/blob/main/Exercise_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Question 1: Docmentation reading on torch.Tensor and torch.cuda
import torch
print(torch.__version__)

2.1.0+cu121


In [31]:
# Question 2: Create a random tensor with shape (7, 7)
random_tensor = torch.rand(size=(7, 7))
print(random_tensor, ' ', random_tensor.shape)

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])   torch.Size([7, 7])


In [32]:
# Question 3: Perform a matrix multiplication on the tnesor from 2 with another random tensor
# with shape (1, 7)
another_random_tensor = torch.rand(size=(1, 7))
result = random_tensor @ another_random_tensor.T
print(result, ' ', result.shape)

tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])   torch.Size([7, 1])


In [35]:
# Question 4: Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)

random_tensor = torch.rand(size=(7, 7))
another_random_tensor = torch.rand(size=(1, 7))

result = random_tensor @ another_random_tensor.T
print(result, ' ', result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])   torch.Size([7, 1])


In [7]:
# Question 5: Speaking of random seeds, we saw how to set it with
# torch.manual_seed() but is there a GPU equivalent?
# (hint: you'll need to look into the documentation for torch.cuda
# for this one). If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [37]:
# Question 6: Create two random tensors of shape (2, 3) and send them both to the
# GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234)
# when creating the tensors (this doesn't have to be the GPU random seed).

device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(1234)

gpu_random_tensor = torch.rand(size=(2,3)).to(device)
print(gpu_random_tensor)

gpu_random_tesnor_2 = torch.rand(size=(2,3)).to(device)
print(gpu_random_tesnor_2)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [38]:
# Question 7: Perform a matrix multiplication on the tensors you created
# in 6 (again, you may have to adjust the shapes of one of the tensors).

result = gpu_random_tensor @ gpu_random_tesnor_2.T
print(result)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


In [39]:
# Question 8: Find the maximum and minimum values of the output of 7.
print(result.max())
print(result.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


In [41]:
# Question 9: Find the maximum and minimum index values of the output of 7.
print(torch.argmax(result))
print(torch.argmin(result))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')


In [42]:
# Question 10: Make a random tensor with shape (1, 1, 1, 10) and
# then create a new tensor with all the 1 dimensions removed to be
# left with a tensor of shape (10). Set the seed to 7 when you create
# it and print out the first tensor and it's shape as well as the second
#  tensor and it's shape.

torch.manual_seed(7)
random_tensor  = torch.rand(size=(1,1,1,1,10))
print('First ', random_tensor)
print('First ', random_tensor.shape)

new_tensor = random_tensor.squeeze()
print('New Tensor ', new_tensor)
print('New Tensor ', new_tensor.shape)


First  tensor([[[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]])
First  torch.Size([1, 1, 1, 1, 10])
New Tensor  tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New Tensor  torch.Size([10])
